[package]
name = "starlink"
version = "0.1.0"
authors = ["Elias Wilken <elias@wlkn.io>"]
edition = "2018"

[dependencies]
tonic = "0.4"
prost = "0.7"

[build-dependencies]
tonic-build = "0.4"

[dev-dependencies]
async-stream = "0.3"
tokio = { version = "1.5", features = ["rt-multi-thread"] }

[workspace]
members = ["codegen"]
