// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UtDisablementCode {
    UnknownState = 0,
    Okay = 1,
    NoActiveAccount = 2,
    TooFarFromServiceAddress = 3,
    InOcean = 4,
    InvalidCountry = 5,
    BlockedCountry = 6,
    DataOverageSandboxPolicy = 7,
    CellIsDisabled = 8,
    UnlicensedCountry = 9,
}
impl UtDisablementCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            UtDisablementCode::UnknownState => "UNKNOWN_STATE",
            UtDisablementCode::Okay => "OKAY",
            UtDisablementCode::NoActiveAccount => "NO_ACTIVE_ACCOUNT",
            UtDisablementCode::TooFarFromServiceAddress => "TOO_FAR_FROM_SERVICE_ADDRESS",
            UtDisablementCode::InOcean => "IN_OCEAN",
            UtDisablementCode::InvalidCountry => "INVALID_COUNTRY",
            UtDisablementCode::BlockedCountry => "BLOCKED_COUNTRY",
            UtDisablementCode::DataOverageSandboxPolicy => "DATA_OVERAGE_SANDBOX_POLICY",
            UtDisablementCode::CellIsDisabled => "CELL_IS_DISABLED",
            UtDisablementCode::UnlicensedCountry => "UNLICENSED_COUNTRY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_STATE" => Some(Self::UnknownState),
            "OKAY" => Some(Self::Okay),
            "NO_ACTIVE_ACCOUNT" => Some(Self::NoActiveAccount),
            "TOO_FAR_FROM_SERVICE_ADDRESS" => Some(Self::TooFarFromServiceAddress),
            "IN_OCEAN" => Some(Self::InOcean),
            "INVALID_COUNTRY" => Some(Self::InvalidCountry),
            "BLOCKED_COUNTRY" => Some(Self::BlockedCountry),
            "DATA_OVERAGE_SANDBOX_POLICY" => Some(Self::DataOverageSandboxPolicy),
            "CELL_IS_DISABLED" => Some(Self::CellIsDisabled),
            "UNLICENSED_COUNTRY" => Some(Self::UnlicensedCountry),
            _ => None,
        }
    }
}
